server:
  port: 7003

eureka:
  instance:
    # Eureka服务端的实例名称
    hostname: server7003.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    serviceUrl:
      # 设置与注册中心交互的地址，查询服务和注册服务都依赖这个地址
      defaultZone: http://server7001.com:7001/eureka/,http://server7002.com:7002/eureka/