server:
  port: 8002

# 获取配置信息: /{label}/{application}-{profile}
# 获取配置文件信息: /{label}/{application}-{profile}.yml
# application：代表应用名称，默认为配置文件中的spring.application.name，如果配置了spring.cloud.config.name，则为该名称；
# label：代表分支名称，对应配置文件中的spring.cloud.config.label；
# profile：代表环境名称，对应配置文件中的spring.cloud.config.profile。
spring:
  application:
    name: cloud-provider-user
  cloud:
    config: #Config客户端配置
      profile: dev #启用配置后缀名称
      label: dev #分支名称
      uri: http://localhost:9001 #配置中心地址
      name: config #配置文件名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # 配置数据库驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud_demo?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true # 将当前服务注册进Eureka服务注册中心，默认为 true
    fetchRegistry: true # 是否从 Eureka Server 抓取已有的注册服务，默认为 true（ps：单节点无所谓，汲取必须设置为true才能配合ribbon使用负载均衡）。
    serviceUrl:
      defaultZone: http://admin:123456@server7001.com:7001/eureka/, http://admin:123456@server7002.com:7002/eureka/

mybatis:
  mapperLocations: classpath:mapper/*.xml # Mybatis 映射文件的扫描路径
  type-aliases-package: com.spring.cloud.common.api.entity # 映射文件对应的映射实体路径